version: '3'
tasks:
  generate:
    cmds:
      - protoc -I proto proto/*/*.proto -I ./third_party/googleapis --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
        
